# Render blueprint • Varcavia infrastructure
#
# - 1)  flowise-varcavia  → container Docker (API + UI)
# - 2)  varcavia-pages    → segnaposto statico (già servito da GitHub Pages)

services:
  # ────────────────────────────────────────────────
  # 1) Flowise (chatbot RAG)
  # ────────────────────────────────────────────────
  - type: web
    name: flowise-varcavia
    env: docker
    region: frankfurt
    plan: free            # se l’immagine > 512 MB passa a “starter”
    rootDir: .
    dockerfilePath: deploy/Dockerfile.flowise
    autoDeploy: false     # eviti rebuild a ogni push

    envVars:
      - key: PORT                # porta esposta dal container
        value: "3000"
      - key: OPENAI_API_KEY       # 4 variabili → da inserire in dashboard
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: FLOWISE_USERNAME
        value: admin
      - key: FLOWISE_PASSWORD
        sync: false

# se vuoi anche un placeholder statico (non obbligatorio)
staticSites:
  - name: varcavia-pages          # slug <name>.onrender.com
    branch: main
    rootDir: .
    buildCommand: ""              # build già fatta da GitHub Pages
    staticPublishPath: ""         # niente da copiare
    autoDeploy: false
