services:
  # ── Web #1: SvelteKit (GitHub Pages) ────────────────────────
  - type: static
    name: varcavia-pages
    env: static
    rootDir: .
    buildCommand: ""
    staticPublishPath: .                             # già gestito da GitHub Pages, ma lasciamo placeholder
    autoDeploy: false

  # ── Web #2: Flowise ─────────────────────────────────────────
  - type: web
    name: flowise-varcavia
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: deploy/Dockerfile.flowise
    autoDeploy: false
    envVars:
      - key: PORT            # obbligatoria su Render
        value: 3000
      - key: OPENAI_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: FLOWISE_USERNAME
        value: admin
      - key: FLOWISE_PASSWORD
        sync: false
