# Render blueprint · Varcavia infrastructure
#
# 1) flowise-varcavia  → container Docker (API + UI)
# 2) varcavia-pages    → placeholder statico (facoltativo)

services:
  # ───────────────────────────────────────────────
  # 1) Flowise  (chatbot RAG)
  # ───────────────────────────────────────────────
  - type: web
    name: flowise-varcavia
    runtime: docker
    region: frankfurt
    plan: free                         # se l’immagine >512 MB passa a “starter”
    rootDir: .
    dockerfilePath: deploy/Dockerfile.flowise
    autoDeploy: false                  # niente rebuild a ogni push
    envVars:
      - key: PORT                      # porta esposta dal container
        value: "3000"

      # ───── variabili da completare in dashboard Render ─────
      - key: OPENAI_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: FLOWISE_PASSWORD
        sync: false

      # costante
      - key: FLOWISE_USERNAME
        value: admin

  # ───────────────────────────────────────────────
  # 2) Placeholder statico (facoltativo)
  # ───────────────────────────────────────────────
  - type: web
    name: varcavia-pages               # slug: <name>.onrender.com
    runtime: static
    branch: main
    rootDir: .                         # sito già buildato da GitHub Pages
    buildCommand: ""                   # nessuna build su Render
    staticPublishPath: ""              # niente da copiare
    autoDeploy: false
