# ==========================================
# Render blueprint • Varcavia infrastructure
# ==========================================

# --- 1) GitHub Pages placeholder -----------
staticSites:
  - name: varcavia-pages        # slug del dominio pubblico
    branch: main
    buildCommand: ""            # non serve: Pages già pubblica
    staticPublishPath: ""       # —
    autoDeploy: false           # non trigga build a ogni push

# --- 2) Flowise API container --------------
services:
  - type: web
    name: flowise-varcavia
    env: docker                 # useremo Dockerfile dedicato
    region: frankfurt
    plan: free                  # passa a “starter” se l’immagine supera 512 MB
    dockerfilePath: deploy/Dockerfile.flowise
    autoDeploy: false           # evita redeploy continuo
    envVars:
      - key: PORT               # porta esposta dal container
        value: "3000"
      - key: OPENAI_API_KEY     # le quattro seguenti vanno compilate via dashboard
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: FLOWISE_USERNAME
        value: admin
      - key: FLOWISE_PASSWORD
        sync: false
