# =========================
# Render blueprint Varcavia
# =========================
services:
  # 1 — Sito SvelteKit (GitHub Pages placeholder)
  - type: static_site          # <-- forma corretta
    name: varcavia-pages
    # Il build e deploy del sito statico è già fatto da GitHub Pages.
    # Qui lasciamo un segnaposto (non verrà mai costruito).
    buildCommand: ""
    staticPublishPath: ""
    autoDeploy: false

  # 2 — Web API: Flowise
  - type: web
    name: flowise-varcavia
    env: docker
    region: frankfurt
    plan: free                 # se build >512 MB passa a “starter”
    dockerfilePath: deploy/Dockerfile.flowise
    autoDeploy: false          # evitiamo redeploy a ogni push
    envVars:
      - key: PORT
        value: "3000"          # Flowise ascolta qui
      - key: OPENAI_API_KEY
        sync: false            # da inserire a mano in dashboard
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: FLOWISE_USERNAME
        value: admin
      - key: FLOWISE_PASSWORD
        sync: false
