name: CI build & typecheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: TypeScript type-check
        run: pnpm dlx tsc -p tsconfig.json

      - name: Bot dry-run compile
        run: pnpm dlx tsc -p packages/bot
