name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        # rimuoviamo --frozen-lockfile e usiamo --no-frozen-lockfile
        run: pnpm install --no-frozen-lockfile

      - name: Generate pnpm lockfile (if missing)
        if: ${{ !exists('pnpm-lock.yaml') }}
        run: pnpm install

      - name: Build & type-check
        run: pnpm exec tsc --noEmit

      - name: Lint
        run: pnpm exec eslint .

