name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      # 3. Node + cache
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      # 4. Install deps
      - run: pnpm install --no-frozen-lockfile

      # 5. Type-check (obbligatorio)
      - run: pnpm exec tsc --noEmit
