name: Librarian-Bot (mainnet)

on:
  schedule:
    - cron: '0 3 * * 1'   # lunedì 03:00 UTC
  workflow_dispatch:

jobs:
  mint:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Run librarian (upload → mint → Qdrant)
        run: pnpm dlx ts-node packages/bot/librarian.ts
        env:
          OPENAI_API_KEY:      ${{ secrets.OPENAI_API_KEY }}
          THIRDWEB_CLIENT_ID:  ${{ secrets.THIRDWEB_CLIENT_ID }}
          THIRDWEB_SECRET_KEY: ${{ secrets.THIRDWEB_SECRET_KEY }}
          LIGHTHOUSE_API_KEY:  ${{ secrets.LIGHTHOUSE_API_KEY }}
          QDRANT_API_KEY:      ${{ secrets.QDRANT_API_KEY }}
          LUMIGO_PRIVATE_KEY:  ${{ secrets.LUMIGO_PRIVATE_KEY }}
