name: Librarian Cron

on:
  workflow_dispatch:      # permette “Run workflow” manuale
  schedule:
    - cron:  '0 2 * * *'  # ogni giorno alle 02 UTC

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run librarian bot
        run: pnpm dlx tsx packages/bot/librarian.ts
        env:
          LH_API_KEY:        ${{ secrets.LH_API_KEY }}
          PKEY_TESTNET:      ${{ secrets.PKEY_TESTNET }}
          TW_CLIENT_ID:      ${{ secrets.TW_CLIENT_ID }}
          TW_SECRET_KEY:     ${{ secrets.TW_SECRET_KEY }}
          DATASET_NFT_CONTRACT: ${{ secrets.DATASET_NFT_CONTRACT }}
          QDRANT_URL:        ${{ secrets.QDRANT_URL }}
          QDRANT_KEY:        ${{ secrets.QDRANT_KEY }}
