name: Librarian Cron
on:
  workflow_dispatch:    # Permette lancio manuale
  schedule:
    - cron: "0 2 * * *"  # Ogni giorno alle 2:00 UTC

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --no-frozen-lockfile     # <--- QUESTA È LA RIGA MODIFICATA
      - run: pnpm dlx tsx -r dotenv/config packages/bot/librarian.ts
        env:
          LH_API_KEY: ${{ secrets.LH_API_KEY }}
          TW_CLIENT_ID: ${{ secrets.TW_CLIENT_ID }}
          TW_SECRET_KEY: ${{ secrets.TW_SECRET_KEY }}
          PKEY_TESTNET: ${{ secrets.PKEY_TESTNET }}
          DATASET_NFT_CONTRACT: ${{ secrets.DATASET_NFT_CONTRACT }}
          QDRANT_URL:  ${{ secrets.QDRANT_URL }}
          QDRANT_KEY:  ${{ secrets.QDRANT_KEY }}
