name: Librarian-Bot (mainnet)

on:
  schedule:
    - cron: '0 3 * * 1'      # Monday 03:00 UTC
  workflow_dispatch:

jobs:
  mint:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10.11.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Run librarian (upload → mint → Qdrant)
        run: pnpm exec tsx -r dotenv/config packages/bot/librarian.ts
        env:
          OPENAI_API_KEY:        ${{ secrets.OPENAI_API_KEY }}
          LH_API_KEY:            ${{ secrets.LH_API_KEY }}
          TW_CLIENT_ID:          ${{ secrets.THIRDWEB_CLIENT_ID }}
          TW_SECRET_KEY:         ${{ secrets.THIRDWEB_SECRET_KEY }}
          LUMIGO_PRIVATE_KEY:    ${{ secrets.LUMIGO_PRIVATE_KEY }}
          DATASET_NFT_CONTRACT:  ${{ secrets.DATASET_NFT_CONTRACT }}
          QDRANT_URL:            ${{ secrets.QDRANT_URL }}
          QDRANT_KEY:            ${{ secrets.QDRANT_KEY }}
