name: Librarian-Bot (mainnet)

on:
  schedule:
    - cron: '0 3 * * 1'   # Monday 03:00 UTC
  workflow_dispatch:

jobs:
  mint:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # 1 — scarica il repo
      - uses: actions/checkout@v4

      # 2 — imposta pnpm 10 + Node 20
      - uses: pnpm/action-setup@v3
        with:
          pnpm-version: 10.11.0
          node-version: 20

      # 3 — installa dipendenze (ora il lockfile è committato)
      - run: pnpm install --frozen-lockfile

      # 4 — esegue lo script librarian
      - name: Run librarian (upload → mint → Qdrant)
        run: pnpm dlx ts-node packages/bot/librarian.ts
        env:
          OPENAI_API_KEY:      ${{ secrets.OPENAI_API_KEY }}
          THIRDWEB_CLIENT_ID:  ${{ secrets.THIRDWEB_CLIENT_ID }}
          THIRDWEB_SECRET_KEY: ${{ secrets.THIRDWEB_SECRET_KEY }}
          LIGHTHOUSE_API_KEY:  ${{ secrets.LIGHTHOUSE_API_KEY }}
          QDRANT_API_KEY:      ${{ secrets.QDRANT_API_KEY }}
          LUMIGO_PRIVATE_KEY:  ${{ secrets.LUMIGO_PRIVATE_KEY }}
