name: Librarian-Bot (mainnet)

on:
  schedule:
    - cron: '0 3 * * 1'   # Monday 03 UTC
  workflow_dispatch:

jobs:
  mint:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 1 — checkout repo
      - uses: actions/checkout@v4

      # 2 — install PNPM 10
      - uses: pnpm/action-setup@v3
        with:
          version: 10.11.0         # <— parametro corretto

      # 3 — install Node 20 & enable pnpm cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # 4 — install deps
      - run: pnpm install --frozen-lockfile

      # 5 — run librarian bot
      - name: Run librarian (upload → mint → Qdrant)
        run: pnpm dlx ts-node packages/bot/librarian.ts
        env:
          OPENAI_API_KEY:      ${{ secrets.OPENAI_API_KEY }}
          THIRDWEB_CLIENT_ID:  ${{ secrets.THIRDWEB_CLIENT_ID }}
          THIRDWEB_SECRET_KEY: ${{ secrets.THIRDWEB_SECRET_KEY }}
          LIGHTHOUSE_API_KEY:  ${{ secrets.LIGHTHOUSE_API_KEY }}
          QDRANT_API_KEY:      ${{ secrets.QDRANT_API_KEY }}
          LUMIGO_PRIVATE_KEY:  ${{ secrets.LUMIGO_PRIVATE_KEY }}
