name: Librarian Cron (testnet)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"   # 02:00 UTC ogni giorno

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          pnpm-version: 8
          node-version: 20

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run librarian bot
        run: pnpm exec tsx -r dotenv/config packages/bot/librarian.ts
        env:
          LH_API_KEY:            ${{ secrets.LH_API_KEY }}
          TW_CLIENT_ID:          ${{ secrets.TW_CLIENT_ID }}
          TW_SECRET_KEY:         ${{ secrets.TW_SECRET_KEY }}
          PKEY_TESTNET:          ${{ secrets.PKEY_TESTNET }}
          DATASET_NFT_CONTRACT:  ${{ secrets.DATASET_NFT_CONTRACT }}
          QDRANT_URL:            ${{ secrets.QDRANT_URL }}
          QDRANT_KEY:            ${{ secrets.QDRANT_KEY }}
